server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html/web; # Chemin vers le dossier public de Drupal
        index index.php index.html;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000; # Vérifie que ton service s'appelle bien 'php' dans docker-compose
        fastcgi_param SCRIPT_FILENAME /var/www/html/web$fastcgi_script_name;
    }
}