server {
    listen 80;
    server_name localhost;
    
    # On définit le root ici pour tout le monde
    root /var/www/html/web;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        # On utilise $document_root pour être sûr que Nginx transmet le bon chemin à PHP
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}